name: Documentation
description: Report an issue related to the NumPy documentation.
title: "[DOCS]: "
labels: [documentation, needs triage]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please leave a reference to the document/code you're
      referring to.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe any topics you think are missing
      from the current documentation.