name: Feature request
description: Suggest a new idea or enhancement
title: "[FEATURE REQUEST]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## Problem description"
  - type: textarea
    id: problem-description
    attributes:
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Suggested solution"
  - type: textarea
    id: suggested-solution
    attributes:
      placeholder: "Describe what you want to happen."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Alternative solutions"
  - type: textarea
    id: alternative-solutions
    attributes:
      placeholder: "Describe any alternative solutions or features you've considered."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Additional context"
  - type: textarea
    id: additional-context
    attributes:
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
