name: Feature request
description: Suggest a new idea or enhancement.
title: "[FEATURE REQUEST]: "
labels: [enhancement, needs triage]

body:
- type: textarea
  attributes:
    label: "The problem you are trying to solve:"
    description: >
      A clear and concise description of what the problem is. Ex. I'm always
      frustrated when [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: "Suggested new feature or change:"
    description: >
      A detailed description on the proposed solution.
  validations:
    required: true